const PRODUCTS = [
  { id:1,  name:'SG Savage Edition Bat',        category:'Bats',          emoji:'🏏', price:4999,  oldPrice:6499,  rating:4.8, reviews:312, tags:['bats'] },
  { id:2,  name:'Kookaburra Bubble Bat',         category:'Bats',          emoji:'🏏', price:3499,  oldPrice:4500,  rating:4.6, reviews:198, tags:['bats'] },
  { id:3,  name:'SS Ton Gladiator Bat',          category:'Bats',          emoji:'🏏', price:5999,  oldPrice:7999,  rating:4.9, reviews:421, tags:['bats'] },
  { id:4,  name:'MRF Grand Edition Bat',         category:'Bats',          emoji:'🏏', price:2999,  oldPrice:3999,  rating:4.4, reviews:143, tags:['bats'] },
  { id:5,  name:'SG Club Match Ball',            category:'Balls',         emoji:'🎾', price:449,   oldPrice:599,   rating:4.5, reviews:87,  tags:['balls'] },
  { id:6,  name:'Kookaburra Turf Ball',          category:'Balls',         emoji:'🎾', price:699,   oldPrice:899,   rating:4.7, reviews:156, tags:['balls'] },
  { id:7,  name:'Dukes English County Ball',     category:'Balls',         emoji:'🎾', price:1299,  oldPrice:1699,  rating:4.8, reviews:203, tags:['balls'] },
  { id:8,  name:'GM Siren Tennis Ball',          category:'Balls',         emoji:'🎾', price:199,   oldPrice:249,   rating:4.2, reviews:44,  tags:['balls'] },
  { id:9,  name:'MI Official Jersey 2026',       category:'IPL Jerseys',   emoji:'👕', price:1299,  oldPrice:1699,  rating:4.9, reviews:634, tags:['jerseys'] },
  { id:10, name:'CSK Dhoni Edition Jersey',      category:'IPL Jerseys',   emoji:'👕', price:1499,  oldPrice:1999,  rating:4.9, reviews:891, tags:['jerseys'] },
  { id:11, name:'RCB Kohli Jersey 2026',         category:'IPL Jerseys',   emoji:'👕', price:1399,  oldPrice:1799,  rating:4.8, reviews:754, tags:['jerseys'] },
  { id:12, name:'KKR Purple Kit 2026',           category:'IPL Jerseys',   emoji:'👕', price:1199,  oldPrice:1549,  rating:4.6, reviews:322, tags:['jerseys'] },
  { id:13, name:'DC Delhi Capitals Jersey',      category:'IPL Jerseys',   emoji:'👕', price:1099,  oldPrice:1399,  rating:4.5, reviews:214, tags:['jerseys'] },
  { id:14, name:'SRH Orange Army Jersey',        category:'IPL Jerseys',   emoji:'👕', price:1199,  oldPrice:1499,  rating:4.7, reviews:388, tags:['jerseys'] },
  { id:15, name:'India Home Test Jersey',        category:'International', emoji:'🌍', price:1799,  oldPrice:2299,  rating:4.9, reviews:512, tags:['international'] },
  { id:16, name:'Australia Away Kit',            category:'International', emoji:'🌍', price:2099,  oldPrice:2699,  rating:4.7, reviews:267, tags:['international'] },
  { id:17, name:'England Test Match Jersey',     category:'International', emoji:'🌍', price:2299,  oldPrice:2999,  rating:4.6, reviews:183, tags:['international'] },
  { id:18, name:'West Indies Maroon Kit',        category:'International', emoji:'🌍', price:1899,  oldPrice:2399,  rating:4.5, reviews:128, tags:['international'] },
  { id:19, name:'SG Wicket-Keeping Gloves',      category:'Gear',          emoji:'🧤', price:1299,  oldPrice:1699,  rating:4.6, reviews:97,  tags:['gear'] },
  { id:20, name:'Kookaburra Batting Pads',       category:'Gear',          emoji:'🛡️', price:2499,  oldPrice:3199,  rating:4.7, reviews:142, tags:['gear'] },
  { id:21, name:'SS Batting Helmet PRO',         category:'Gear',          emoji:'⛑️', price:1999,  oldPrice:2599,  rating:4.8, reviews:221, tags:['gear'] },
  { id:22, name:'GM Cricket Bag Duffle',         category:'Gear',          emoji:'🎒', price:2999,  oldPrice:3999,  rating:4.5, reviews:89,  tags:['gear'] },
];
